# Generated by Django 6.0.3 on 2026-04-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('seller', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('product_dimensions', models.CharField(max_length=100)),
            ],
        ),
    ]
